@echo off
cls
timeout /t 1 /nobreak >nul
cd %~dp0
timeout /t 1 /nobreak >nul
cls
taskkill /f /pid ActApp.exe
taskkill /f /pid AudioCapture.dll
taskkill /f /pid blockapp.jpg
taskkill /f /pid clhook4.dll
taskkill /f /pid client32.exe
taskkill /f /pid Client32.ini
taskkill /f /pid Client32Provider.dll
taskkill /f /pid comclaex.dll
taskkill /f /pid Control.kbd
taskkill /f /pid DBI.EXE
taskkill /f /pid Dummy.Lic
taskkill /f /pid gdihook5.cat
taskkill /f /pid gdihook5.INF
taskkill /f /pid gdiplus.dll
taskkill /f /pid htctl32.dll
taskkill /f /pid image_name.jpg
taskkill /f /pid imhook.dll
taskkill /f /pid injlib.dll
taskkill /f /pid IPCTL32.DLL
taskkill /f /pid ismetro.exe
taskkill /f /pid keyshow.exe
taskkill /f /pid keyShow64.exe
taskkill /f /pid keyshowhook.dll
taskkill /f /pid KeyShowHook64.dll
taskkill /f /pid libhpdf.dll
taskkill /f /pid mfc100u.dll
taskkill /f /pid msvcp100.dll
taskkill /f /pid msvcr100.dll
taskkill /f /pid Nbctl32.dll
taskkill /f /pid NBCTLA0.DLL
taskkill /f /pid NBCTLA1.DLL
taskkill /f /pid NBCTLA2.DLL
taskkill /f /pid NBCTLA3.DLL
taskkill /f /pid NBCTLA4.DLL
taskkill /f /pid NBCTLA5.DLL
taskkill /f /pid NBCTLA6.DLL
taskkill /f /pid NBCTLA7.DLL
taskkill /f /pid nskbfltr.inf
taskkill /f /pid nskbfltr.sys
taskkill /f /pid NSM.LIC
taskkill /f /pid nsmexec.exe
taskkill /f /pid NSS.ini
taskkill /f /pid NSS32.chm
taskkill /f /pid NSSecurity.dll
taskkill /f /pid NSSilence.exe
taskkill /f /pid nssplayercore.dll
taskkill /f /pid nssres.dll
taskkill /f /pid nss_lock_image.jpg
taskkill /f /pid nss_lock_image_ws.jpg
taskkill /f /pid NSToast.exe
taskkill /f /pid PCIAPPCTRL.DLL
taskkill /f /pid pciappctrl64.dll
taskkill /f /pid pcicapi.DLL
taskkill /f /pid pcicfgui.exe
taskkill /f /pid PCICHEK.DLL
taskkill /f /pid PCICL32.DLL
taskkill /f /pid PCICTL.DLL
taskkill /f /pid PCIHOOKS.DLL
taskkill /f /pid PCIIMAGE.DLL
taskkill /f /pid pciinv.dll
taskkill /f /pid pcijoin.exe
taskkill /f /pid PCIMSG.DLL
taskkill /f /pid PCINSSCD.EXE
taskkill /f /pid PCIRES.dll
taskkill /f /pid pcisys.sys
taskkill /f /pid PCIVDD.DLL
taskkill /f /pid PCIVIDEO.EXE
taskkill /f /pid pcivideovi.exe
taskkill /f /pid PlaySound.exe
taskkill /f /pid PluginCountersModule.dll
taskkill /f /pid PluginDevicesModule.dll
taskkill /f /pid PluginDevicesModule64.dll
taskkill /f /pid pluginiemodule.DLL
taskkill /f /pid pluginimmodule.dll
taskkill /f /pid pluginprintmanmodule.dll
taskkill /f /pid pluginprintmanmodule64.dll
taskkill /f /pid pluginsoftwaremodule.DLL
taskkill /f /pid PluginSoftwareModule64.dll
taskkill /f /pid product.dat
taskkill /f /pid remcmdstub.exe
taskkill /f /pid ReportDb.htf
taskkill /f /pid runplugin.exe
taskkill /f /pid Runplugin64.exe
taskkill /f /pid schplayer.exe
taskkill /f /pid sec.log
taskkill /f /pid setroom.exe
taskkill /f /pid shfolder.dll
taskkill /f /pid startlogo.bmp
taskkill /f /pid StoreSoftwareCtl.dll
taskkill /f /pid StoreSoftwareCtl64.dll
taskkill /f /pid StudentUI.exe
taskkill /f /pid supporttool.exe
taskkill /f /pid TCCTL32.DLL
taskkill /f /pid toastImageAndText.png
taskkill /f /pid UNZDLL.DLL
taskkill /f /pid url_list.gif
taskkill /f /pid VolumeControlWVI.DLL
taskkill /f /pid VolumeControlWXP.DLL
taskkill /f /pid WdfCoInstaller01005.dll
taskkill /f /pid weblock.htm
taskkill /f /pid weblock.jpg
taskkill /f /pid winst64.exe
taskkill /f /pid WINSTALL.EXE
taskkill /f /pid ZIPDLL.DLL
taskkill /f /IM ActApp.exe
taskkill /f /IM AudioCapture.dll
taskkill /f /IM blockapp.jpg
taskkill /f /IM clhook4.dll
taskkill /f /IM client32.exe
taskkill /f /IM Client32.ini
taskkill /f /IM Client32Provider.dll
taskkill /f /IM comclaex.dll
taskkill /f /IM Control.kbd
taskkill /f /IM DBI.EXE
taskkill /f /IM Dummy.Lic
taskkill /f /IM gdihook5.cat
taskkill /f /IM gdihook5.INF
taskkill /f /IM gdiplus.dll
taskkill /f /IM htctl32.dll
taskkill /f /IM image_name.jpg
taskkill /f /IM imhook.dll
taskkill /f /IM injlib.dll
taskkill /f /IM IPCTL32.DLL
taskkill /f /IM ismetro.exe
taskkill /f /IM keyshow.exe
taskkill /f /IM keyShow64.exe
taskkill /f /IM keyshowhook.dll
taskkill /f /IM KeyShowHook64.dll
taskkill /f /IM libhpdf.dll
taskkill /f /IM mfc100u.dll
taskkill /f /IM msvcp100.dll
taskkill /f /IM msvcr100.dll
taskkill /f /IM Nbctl32.dll
taskkill /f /IM NBCTLA0.DLL
taskkill /f /IM NBCTLA1.DLL
taskkill /f /IM NBCTLA2.DLL
taskkill /f /IM NBCTLA3.DLL
taskkill /f /IM NBCTLA4.DLL
taskkill /f /IM NBCTLA5.DLL
taskkill /f /IM NBCTLA6.DLL
taskkill /f /IM NBCTLA7.DLL
taskkill /f /IM nskbfltr.inf
taskkill /f /IM nskbfltr.sys
taskkill /f /IM NSM.LIC
taskkill /f /IM nsmexec.exe
taskkill /f /IM NSS.ini
taskkill /f /IM NSS32.chm
taskkill /f /IM NSSecurity.dll
taskkill /f /IM NSSilence.exe
taskkill /f /IM nssplayercore.dll
taskkill /f /IM nssres.dll
taskkill /f /IM nss_lock_image.jpg
taskkill /f /IM nss_lock_image_ws.jpg
taskkill /f /IM NSToast.exe
taskkill /f /IM PCIAPPCTRL.DLL
taskkill /f /IM pciappctrl64.dll
taskkill /f /IM pcicapi.DLL
taskkill /f /IM pcicfgui.exe
taskkill /f /IM PCICHEK.DLL
taskkill /f /IM PCICL32.DLL
taskkill /f /IM PCICTL.DLL
taskkill /f /IM PCIHOOKS.DLL
taskkill /f /IM PCIIMAGE.DLL
taskkill /f /IM pciinv.dll
taskkill /f /IM pcijoin.exe
taskkill /f /IM PCIMSG.DLL
taskkill /f /IM PCINSSCD.EXE
taskkill /f /IM PCIRES.dll
taskkill /f /IM pcisys.sys
taskkill /f /IM PCIVDD.DLL
taskkill /f /IM PCIVIDEO.EXE
taskkill /f /IM pcivideovi.exe
taskkill /f /IM PlaySound.exe
taskkill /f /IM PluginCountersModule.dll
taskkill /f /IM PluginDevicesModule.dll
taskkill /f /IM PluginDevicesModule64.dll
taskkill /f /IM pluginiemodule.DLL
taskkill /f /IM pluginimmodule.dll
taskkill /f /IM pluginprintmanmodule.dll
taskkill /f /IM pluginprintmanmodule64.dll
taskkill /f /IM pluginsoftwaremodule.DLL
taskkill /f /IM PluginSoftwareModule64.dll
taskkill /f /IM product.dat
taskkill /f /IM remcmdstub.exe
taskkill /f /IM ReportDb.htf
taskkill /f /IM runplugin.exe
taskkill /f /IM Runplugin64.exe
taskkill /f /IM schplayer.exe
taskkill /f /IM sec.log
taskkill /f /IM setroom.exe
taskkill /f /IM shfolder.dll
taskkill /f /IM startlogo.bmp
taskkill /f /IM StoreSoftwareCtl.dll
taskkill /f /IM StoreSoftwareCtl64.dll
taskkill /f /IM StudentUI.exe
taskkill /f /IM supporttool.exe
taskkill /f /IM TCCTL32.DLL
taskkill /f /IM toastImageAndText.png
taskkill /f /IM UNZDLL.DLL
taskkill /f /IM url_list.gif
taskkill /f /IM VolumeControlWVI.DLL
taskkill /f /IM VolumeControlWXP.DLL
taskkill /f /IM WdfCoInstaller01005.dll
taskkill /f /IM weblock.htm
taskkill /f /IM weblock.jpg
taskkill /f /IM winst64.exe
taskkill /f /IM WINSTALL.EXE
taskkill /f /IM ZIPDLL.DLL
taskkill /f /pid ActApp
taskkill /f /pid AudioCapture
taskkill /f /pid blockapp
taskkill /f /pid clhook4
taskkill /f /pid client32
taskkill /f /pid Client32
taskkill /f /pid Client32Provider
taskkill /f /pid comclaex
taskkill /f /pid Control
taskkill /f /pid DBI
taskkill /f /pid Dummy
taskkill /f /pid gdihook5
taskkill /f /pid gdihook5
taskkill /f /pid gdiplus
taskkill /f /pid htctl32
taskkill /f /pid image_name
taskkill /f /pid imhook
taskkill /f /pid injlib
taskkill /f /pid IPCTL32
taskkill /f /pid ismetro
taskkill /f /pid keyshow
taskkill /f /pid keyShow64
taskkill /f /pid keyshowhook
taskkill /f /pid KeyShowHook64
taskkill /f /pid libhpdf
taskkill /f /pid mfc100u
taskkill /f /pid msvcp100
taskkill /f /pid msvcr100
taskkill /f /pid Nbctl32
taskkill /f /pid NBCTLA0
taskkill /f /pid NBCTLA1
taskkill /f /pid NBCTLA2
taskkill /f /pid NBCTLA3
taskkill /f /pid NBCTLA4
taskkill /f /pid NBCTLA5
taskkill /f /pid NBCTLA6
taskkill /f /pid NBCTLA7
taskkill /f /pid nskbfltr
taskkill /f /pid nskbfltr
taskkill /f /pid NSM
taskkill /f /pid nsmexec
taskkill /f /pid NSS
taskkill /f /pid NSS32
taskkill /f /pid NSSecurity
taskkill /f /pid NSSilence
taskkill /f /pid nssplayercore
taskkill /f /pid nssres
taskkill /f /pid nss_lock_image
taskkill /f /pid nss_lock_image_ws
taskkill /f /pid NSToast
taskkill /f /pid PCIAPPCTRL
taskkill /f /pid pciappctrl64
taskkill /f /pid pcicapi
taskkill /f /pid pcicfgui
taskkill /f /pid PCICHEK
taskkill /f /pid PCICL32
taskkill /f /pid PCICTL
taskkill /f /pid PCIHOOKS
taskkill /f /pid PCIIMAGE
taskkill /f /pid pciinv
taskkill /f /pid pcijoin
taskkill /f /pid PCIMSG
taskkill /f /pid PCINSSCD
taskkill /f /pid PCIRES
taskkill /f /pid pcisys
taskkill /f /pid PCIVDD
taskkill /f /pid PCIVIDEO
taskkill /f /pid pcivideovi
taskkill /f /pid PlaySound
taskkill /f /pid PluginCountersModule
taskkill /f /pid PluginDevicesModule
taskkill /f /pid PluginDevicesModule64
taskkill /f /pid pluginiemodule
taskkill /f /pid pluginimmodule
taskkill /f /pid pluginprintmanmodule
taskkill /f /pid pluginprintmanmodule64
taskkill /f /pid pluginsoftwaremodule
taskkill /f /pid PluginSoftwareModule64
taskkill /f /pid product
taskkill /f /pid remcmdstub
taskkill /f /pid ReportDb
taskkill /f /pid runplugin
taskkill /f /pid Runplugin64
taskkill /f /pid schplayer
taskkill /f /pid sec
taskkill /f /pid setroom
taskkill /f /pid shfolder
taskkill /f /pid startlogo
taskkill /f /pid StoreSoftwareCtl
taskkill /f /pid StoreSoftwareCtl64
taskkill /f /pid StudentUI
taskkill /f /pid supporttool
taskkill /f /pid TCCTL32
taskkill /f /pid toastImageAndText
taskkill /f /pid UNZDLL
taskkill /f /pid url_list
taskkill /f /pid VolumeControlWVI
taskkill /f /pid VolumeControlWXP
taskkill /f /pid WdfCoInstaller01005
taskkill /f /pid weblock
taskkill /f /pid weblock
taskkill /f /pid winst64
taskkill /f /pid WINSTALL
taskkill /f /pid ZIPDLL
taskkill /f /IM ActApp
taskkill /f /IM AudioCapture
taskkill /f /IM blockapp
taskkill /f /IM clhook4
taskkill /f /IM client32
taskkill /f /IM Client32
taskkill /f /IM Client32Provider
taskkill /f /IM comclaex
taskkill /f /IM Control
taskkill /f /IM DBI
taskkill /f /IM Dummy
taskkill /f /IM gdihook5
taskkill /f /IM gdihook5
taskkill /f /IM gdiplus
taskkill /f /IM htctl32
taskkill /f /IM image_name
taskkill /f /IM imhook
taskkill /f /IM injlib
taskkill /f /IM IPCTL32
taskkill /f /IM ismetro
taskkill /f /IM keyshow
taskkill /f /IM keyShow64
taskkill /f /IM keyshowhook
taskkill /f /IM KeyShowHook64
taskkill /f /IM libhpdf
taskkill /f /IM mfc100u
taskkill /f /IM msvcp100
taskkill /f /IM msvcr100
taskkill /f /IM Nbctl32
taskkill /f /IM NBCTLA0
taskkill /f /IM NBCTLA1
taskkill /f /IM NBCTLA2
taskkill /f /IM NBCTLA3
taskkill /f /IM NBCTLA4
taskkill /f /IM NBCTLA5
taskkill /f /IM NBCTLA6
taskkill /f /IM NBCTLA7
taskkill /f /IM nskbfltr
taskkill /f /IM nskbfltr
taskkill /f /IM NSM
taskkill /f /IM nsmexec
taskkill /f /IM NSS
taskkill /f /IM NSS32
taskkill /f /IM NSSecurity
taskkill /f /IM NSSilence
taskkill /f /IM nssplayercore
taskkill /f /IM nssres
taskkill /f /IM nss_lock_image
taskkill /f /IM nss_lock_image_ws
taskkill /f /IM NSToast
taskkill /f /IM PCIAPPCTRL
taskkill /f /IM pciappctrl64
taskkill /f /IM pcicapi
taskkill /f /IM pcicfgui
taskkill /f /IM PCICHEK
taskkill /f /IM PCICL32
taskkill /f /IM PCICTL
taskkill /f /IM PCIHOOKS
taskkill /f /IM PCIIMAGE
taskkill /f /IM pciinv
taskkill /f /IM pcijoin
taskkill /f /IM PCIMSG
taskkill /f /IM PCINSSCD
taskkill /f /IM PCIRES
taskkill /f /IM pcisys
taskkill /f /IM PCIVDD
taskkill /f /IM PCIVIDEO
taskkill /f /IM pcivideovi
taskkill /f /IM PlaySound
taskkill /f /IM PluginCountersModule
taskkill /f /IM PluginDevicesModule
taskkill /f /IM PluginDevicesModule64
taskkill /f /IM pluginiemodule
taskkill /f /IM pluginimmodule
taskkill /f /IM pluginprintmanmodule
taskkill /f /IM pluginprintmanmodule64
taskkill /f /IM pluginsoftwaremodule
taskkill /f /IM PluginSoftwareModule64
taskkill /f /IM product
taskkill /f /IM remcmdstub
taskkill /f /IM ReportDb
taskkill /f /IM runplugin
taskkill /f /IM Runplugin64
taskkill /f /IM schplayer
taskkill /f /IM sec
taskkill /f /IM setroom
taskkill /f /IM shfolder
taskkill /f /IM startlogo
taskkill /f /IM StoreSoftwareCtl
taskkill /f /IM StoreSoftwareCtl64
taskkill /f /IM StudentUI
taskkill /f /IM supporttool
taskkill /f /IM TCCTL32
taskkill /f /IM toastImageAndText
taskkill /f /IM UNZDLL
taskkill /f /IM url_list
taskkill /f /IM VolumeControlWVI
taskkill /f /IM VolumeControlWXP
taskkill /f /IM WdfCoInstaller01005
taskkill /f /IM weblock
taskkill /f /IM weblock
taskkill /f /IM winst64
taskkill /f /IM WINSTALL
taskkill /f /IM ZIPDLL
timeout /t 2 /nobreak >nul
cls
taskkill /f /pid explorer.exe
cls
timeout /t 4 /nobreak >nul
cls
start explorer.exe
cls
timeout /t 3 /nobreak >nul
cls
PowerShell.exe -ExecutionPolicy Unrestricted -command "%~dp0\extra_safe_dsce.ps1"
cls
exit
